### PR TITLE
Fixes for 1.0.1

### PR DESCRIPTION
**Pull request by jedrzej**
This change is [Reviewable](https://reviewable.io/reviews/x-team/x-map/175)

### CODE REVIEW

**Comment by diegodurli** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[client/js/components/pages/ProfilesPage.js, line 6 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkDqKoQKrbM-_pAEXn:-KHkDqKoQKrbM-_pAEXo:-1981028842) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L6)):_

> ``` JavaScript
> import { Link } from 'react-router';
> import DocumentTitle from 'react-document-title';
> import { sortUsersByName } from '../../utils/common';
> ```

Hi Jed, great idea to make it common to use, makes it reusable!
I would only bring some "functional" to the table about it.

My idea for common would be like this:

```
import R from 'ramda';

const fullname = (first, last) => R.join(' ', [first, last]);

function sortByName(name1, name2) {
  return (name1 < name2) ? -1 :
          (name1 > name2) ? 1 : 0;
}

const sortUsersByName = (user1, user2) => {
  return sortByName.bind(this, fullname(user1.firstName, user1.lastName), fullname(user2.firstName, user2.lastName));
};

const sortTeamsByName = (team1, team2) => sortByName.bind(this, team1.name, team2.name);
```

Only to make it more composable and keep it DRY.

---

_[client/js/components/pages/ProfilesPage.js, line 22 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkEkQTJQQCbQykgdAB:-KHkEkQTJQQCbQykgdAC:1760678696) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L22)):_

> ``` JavaScript
>   }
> 
>   render() {
> ```

Talking about functional, my proposal for this part would be:

```
const UserListItem = (props) => (
  <li className="list-group-item" key={props.id}>
    {props.firstName + ' ' + props.lastName}
  </li>
);

class ProfilesPage extends React.Component {
  render() {
    const { users } = this.props,
      profiles = R.compose(
        R.map((user) => <UserListItem {...user} />),
        R.sort(sortUsersByName),
        R.values
      )(users);

    return (
      <div>
        {profiles || <p className="alert error">Something has gone wrong. No profiles found.</p>}
      </div>
    );
  }
}
```

This is just an example and doesn't include all HTML from this render, only the necessary.
It would make it simpler in my opinion.

You can see it here: https://jsbin.com/kofutip/6/edit?js,console,output

---

_[client/js/components/pages/TeamsPage.js, line 28 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkFUnKOnr442f4UstF:-KHkFUnKOnr442f4UstG:-1485607695) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/TeamsPage.js#L28)):_

> ``` JavaScript
>     const { teams, isAdmin } = this.props;
> 
>     const profileObjects = [];
> ```

Here we could take advantage of those R.compose functions.

---

_[client/js/utils/common.js, line 1 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkGmaUldn-ht7thogc:-KHkGmaVt1GKgwIPPNyR:1264991495) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/utils/common.js#L1)):_

> ``` JavaScript
> export function sortUsersByName(user1, user2) {
> ```

All proposals for this common.js were made on the first comment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by jedrzej** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[client/js/components/pages/ProfilesPage.js, line 6 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkDqKoQKrbM-_pAEXn:-KIr_SW2U1-6RfWNnzZd:-898918127) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L6)):_
<details><summary>

<i>Previously, diegodurli (Diego Durli) wrote…</i></summary>



> Hi Jed, great idea to make it common to use, makes it reusable!
> I would only bring some "functional" to the table about it.
> 
> My idea for common would be like this:
> 
> ```
> import R from 'ramda';
> 
> const fullname = (first, last) => R.join(' ', [first, last]);
> 
> function sortByName(name1, name2) {
>   return (name1 < name2) ? -1 :
>           (name1 > name2) ? 1 : 0;
> }
> 
> const sortUsersByName = (user1, user2) => {
>   return sortByName.bind(this, fullname(user1.firstName, user1.lastName), fullname(user2.firstName, user2.lastName));
> };
> 
> const sortTeamsByName = (team1, team2) => sortByName.bind(this, team1.name, team2.name);
> ```
> 
> Only to make it more composable and keep it DRY.
> </details>
> Thanks for the tip, I've refactored the code. I've skipped adding ramda lib though. As it's a kind of a learning project I'm not sure it's good introduce too many new technologies/libs/paradigms at once. I'd love to first check if everyone is ok with that move and then start using everywhere in the project where it makes sense. I really like the lib so I hope we can include it soon.

---

_[client/js/components/pages/ProfilesPage.js, line 22 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkEkQTJQQCbQykgdAB:-KIrfqnHC1M_F00xzbow:-2047622267) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L22)):_
<details><summary>

<i>Previously, diegodurli (Diego Durli) wrote…</i></summary>



> Talking about functional, my proposal for this part would be:
> 
> ```
> const UserListItem = (props) => (
>   <li className="list-group-item" key={props.id}>
>     {props.firstName + ' ' + props.lastName}
>   </li>
> );
> 
> class ProfilesPage extends React.Component {
>   render() {
>     const { users } = this.props,
>       profiles = R.compose(
>         R.map((user) => <UserListItem {...user} />),
>         R.sort(sortUsersByName),
>         R.values
>       )(users);
> 
>     return (
>       <div>
>         {profiles || <p className="alert error">Something has gone wrong. No profiles found.</p>}
>       </div>
>     );
>   }
> }
> ```
> 
> This is just an example and doesn't include all HTML from this render, only the necessary.
> It would make it simpler in my opinion.
> 
> You can see it here: https://jsbin.com/kofutip/6/edit?js,console,output
> </details>
> I've refactored the code a bit, it's now much simpler but again I've skipped ramda lib for the reasons described earlier. TBH I can't wait till we start using it as it seems it could make most of the processing we do in our components much simpler.

---

_[client/js/components/pages/TeamsPage.js, line 28 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkFUnKOnr442f4UstF:-KIrc7YvrckXB6K99Dim:1240993694) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/TeamsPage.js#L28)):_
<details><summary>

<i>Previously, diegodurli (Diego Durli) wrote…</i></summary>



> Here we could take advantage of those R.compose functions.
> </details>
> See the reply to your first comment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by diegodurli** [comment]
_[client/js/components/pages/ProfilesPage.js, line 6 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkDqKoQKrbM-_pAEXn:-KJHzsS-iqvptOqXoEWU:1857642182) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L6)):_
<details><summary>

<i>Previously, jedrzej wrote…</i></summary>



> Thanks for the tip, I've refactored the code. I've skipped adding ramda lib though. As it's a kind of a learning project I'm not sure it's good introduce too many new technologies/libs/paradigms at once. I'd love to first check if everyone is ok with that move and then start using everywhere in the project where it makes sense. I really like the lib so I hope we can include it soon.
> </details>
> Sure Jed, no problem at all. I just think Ramda is a helper lib, just like underscore or any other lib. Happens that Ramda is just functional entirely. Can we start this discussion? Mainly because I've added Ramda to one branch "errorsReducers" I guess, to merge objects. Ramda has several helpers, and I thought that would be OK using the "merge" function. If thats not fine, no problem, just let me know.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by diegodurli** [comment]
_[client/js/components/pages/ProfilesPage.js, line 22 [r1]](https://reviewable.io:443/reviews/x-team/x-map/175#-KHkEkQTJQQCbQykgdAB:-KJI-nKwv6i4QYKJj1Ts:1033100402) ([raw file](https://github.com/x-team/x-map/blob/738a71708e85e430f5ea47007413943b01f90b29/client/js/components/pages/ProfilesPage.js#L22)):_
<details><summary>

<i>Previously, jedrzej wrote…</i></summary>



> I've refactored the code a bit, it's now much simpler but again I've skipped ramda lib for the reasons described earlier. TBH I can't wait till we start using it as it seems it could make most of the processing we do in our components much simpler.
> </details>
> Thats exactly it Jed! Ramda allow us to compose functions to make processing so much easier. IMHO I think we should start this discussion with the team to see if they agree or not on it's usage on this project. I think it would help a lot!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by diegodurli** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by diegodurli** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Comment by diegodurli** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/175)_

**Pull request merged**
