### PR TITLE
Fix #125 Add unit tests for reducers

### LINKED ISSUE #125: Add unit tests for reducers
We have some tests, but not for all reducers. They don't cover all actions. Initial states used in testing and in reducers should be unified as well.

### PR DESCRIPTION
**Pull request by diegodurli**
Add tests specifically to **usersReducer.js**
- Other reducers will be handled in other issues. Already talked with @jedrzej about it.
- It will be easier to review and deal with PR's.

---

This change is [Reviewable](https://reviewable.io/reviews/x-team/x-map/180)

### CODE REVIEW

**Comment by bernardodiasc** [comment]
nice! 👍

**Comment by jedrzej** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[client/js/reducers/usersReducer.js, line 18 [r1]](https://reviewable.io:443/reviews/x-team/x-map/180#-KIrhuYQMfeRY5umlKSy:-KIrhuYQMfeRY5umlKSz:1221207765) ([raw file](https://github.com/x-team/x-map/blob/941fc78bd9d7c3cc030cd8538fedab46f89e2dea/client/js/reducers/usersReducer.js#L18)):_

> ``` JavaScript
> 
> // Export initial state to avoid repetition on tests.
> export const initialState = {};
> ```

I was thinking if it would't be better if initial state was not an empty object but an object that contains all possible properties with their default or empty values? Then we'd have a single place where we could check what properties we can expect to get in the users sate.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/180)_

**Comment by jedrzej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/x-team/x-map/180#-KIrkcamkKv28gBc6Ymn:-KIrkcamkKv28gBc6Ymo:2054968198) (no related file):_
I love the tests, now that I have a good example how to build them I'll pick up some other missing tests task and help with that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/180)_

**Comment by diegodurli** [comment]
_[client/js/reducers/usersReducer.js, line 18 [r1]](https://reviewable.io:443/reviews/x-team/x-map/180#-KIrhuYQMfeRY5umlKSy:-KJHs3KSNkPNZBelEvJB:-733837865) ([raw file](https://github.com/x-team/x-map/blob/941fc78bd9d7c3cc030cd8538fedab46f89e2dea/client/js/reducers/usersReducer.js#L18)):_
<details><summary>

<i>Previously, jedrzej wrote…</i></summary>



> I was thinking if it would't be better if initial state was not an empty object but an object that contains all possible properties with their default or empty values? Then we'd have a single place where we could check what properties we can expect to get in the users sate.
> </details>
> Got your idea and agree 100% with it, would be better to have a full declared object for this initial state, however, this state is about user ids, therefore we can't fill it with initial values. Am I missing something?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/180)_

**Comment by diegodurli** [comment]
_[a discussion](https://reviewable.io:443/reviews/x-team/x-map/180#-KIrkcamkKv28gBc6Ymn:-KJHsiM9HMU1gmCg-dOq:-866754002) (no related file):_
<details><summary>

<i>Previously, jedrzej wrote…</i></summary>



> I love the tests, now that I have a good example how to build them I'll pick up some other missing tests task and help with that.
> </details>
> Thanks Jed! Would like to mention that there's repetition over these tests, mainly due to the nature of these reducers (they have a lot in common). We could reuse parts of the test, or refactor the reducers. Either way would be good to avoid repetition.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/180)_

**Comment by jedrzej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[client/js/reducers/usersReducer.js, line 18 [r1]](https://reviewable.io:443/reviews/x-team/x-map/180#-KIrhuYQMfeRY5umlKSy:-KJfidcGhaIWP_IIk5Nh:475591954) ([raw file](https://github.com/x-team/x-map/blob/941fc78bd9d7c3cc030cd8538fedab46f89e2dea/client/js/reducers/usersReducer.js#L18)):_
<details><summary>

<i>Previously, diegodurli (Diego Durli) wrote…</i></summary>



> Got your idea and agree 100% with it, would be better to have a full declared object for this initial state, however, this state is about user ids, therefore we can't fill it with initial values. Am I missing something?
> </details>
> Hmm, you're right, here it doesn't make sense. I was thinking about reducers in general, e.g. in sessionreducer it would make more sense.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/x-team/x-map/180)_

**Comment by diegodurli** [comment]
Just noticed that some conflicts happened here. Will do it on a fresh branch.

**Pull request closed without merging**
